TREASURE_MAP = []
TREASURE_MAP.append(['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', 'x', 'x'])
TREASURE_MAP.append(['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'])
TREASURE_MAP.append(['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'])
TREASURE_MAP.append(['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'])
TREASURE_MAP.append(['.', '.', 'x', 'x', 'x', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'])
TREASURE_MAP.append(['.', '.', 'x', 'x', 'x', '.', '.', 'x', 'x', 'x', '.', '.', '.', '.', '.'])
TREASURE_MAP.append(['.', '.', 'x', 'x', 'x', '.', '.', 'x', 'x', 'x', 'x', 'x', 'x', '.', '.'])
TREASURE_MAP.append(['.', '.', '.', '.', '.', '.', '.', 'x', 'x', 'x', 'x', 'x', 'x', '.', '.'])
TREASURE_MAP.append(['.', '.', '.', '.', '.', '.', '.', 'x', 'x', '.', '.', '.', '.', 'x', 'x'])
TREASURE_MAP.append(['.', 'x', 'x', 'x', 'x', '.', '.', 'x', 'x', '.', '.', '.', '.', 'x', 'x'])
TREASURE_MAP.append(['.', 'x', 'x', 'x', 'x', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'])
TREASURE_MAP.append(['.', 'x', 'x', 'x', '.', 'x', 'x', 'x', 'x', 'x', '.', '.', '.', '.', '.'])
TREASURE_MAP.append(['.', '.', '.', '.', '.', 'x', 'x', 'x', 'x', 'x', '.', '.', '.', 'x', 'x'])
TREASURE_MAP.append(['.', 'x', 'x', '.', '.', 'x', 'x', 'x', '.', '.', '.', '.', '.', 'x', 'x'])
TREASURE_MAP.append(['.', 'x', 'x', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'])

TRANSIT_MAP = []
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('...............'))
TRANSIT_MAP.append(list('...............'))
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('...............'))
TRANSIT_MAP.append(list('...............'))
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('    ..   ..    '))
TRANSIT_MAP.append(list('    ..   ..    '))

TRANSIT_MAP = []
for i1 in range(5):
    TRANSIT_MAP.append(list('               '))
TRANSIT_MAP.append(list('         ..    '))
TRANSIT_MAP.append(list('         ..    '))
TRANSIT_MAP.append(list('         ..    '))
TRANSIT_MAP.append(list('         ..    '))
TRANSIT_MAP.append(list('         ..    '))
for i1 in range(5):
    TRANSIT_MAP.append(list('               '))
